--- 
  # Play1 - Kubernetes Server installation
  - name: Play - Kubernetes Server installation
    hosts: all
    become: yes
    become_user: root
    tasks:
      - name: Download and install the latest version of k3s
        shell: curl -sfL https://get.k3s.io | sh -s server --disable traefik --disable servicelb

      - name: Install MetalLB
        shell: /usr/local/bin/kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.4/config/manifests/metallb-native.yaml

      - name: Apply MetalLB IP range for home network
        shell: kubectl apply -f https://raw.githubusercontent.com/TheRyanMonty/HomeLab/main/K3S/metallb-config.yaml

      - name: Install the Kubernetes Dashboard web UI
        shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.4.0/aio/deploy/recommended.yaml

      - name: Allow the kubernetes dashboard web UI to be accessible
        shell: kubectl apply -f https://raw.githubusercontent.com/TheRyanMonty/HomeLab/main/K3S/kubernetes-dashboard-assist.yaml

      - name: Install Longhorn for storage management
        shell: kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.2.2/deploy/longhorn.yaml
        
      - name: Allow Longhorn web ui to be accessible
        shell: kubectl apply -f https://raw.githubusercontent.com/TheRyanMonty/HomeLab/main/K3S/longhorn-expose-frontend.yaml

      - name: Update default storageclass for longhorn
        shell: kubectl patch storageclass longhorn -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

      - name: Update default storageclass for local-path
        shell: kubectl patch storageclass local-path -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'

      - name: Update kubernetes to not run workloads on the server
        shell: kubectl taint nodes pm-k3s-s1 key1=value1:NoSchedule



